### ISSUE TITLE
Export flows from pcap file on flow termination or after timeout.

### ISSUE THREAD

**Issue by mielverkerken** [openargus/argus#12]
I use `argus` to read a pcap file captured by `tcpdump` and `ra` to export the argus file to CSV.

Command I use:
`argus -r "dump.pcap" -w - | ra -r - -c, > "argus.csv"`

The command above prints the flows before they are terminated, writing multiple rows for the same network flow. When I play with the `-S` option I can modify this behavior but flows never seem to be outputted on flow termination (TCP FIN or RST) causing 2 flows with the same 5 tuple to be merged when I increase the interval.

Can I change the command above to export the flows from my pcap on flow termination or inactivity timeout?

**Comment by openargus** [comment]
Yes, argus generates status records for flows.  If you are interested in real-time notifications, you can’t wait until the flow closes to report the flow.  Intruders would just not close their connections, which we saw a lot of in the 90’s.

About 95% of flows (in enterprises) live for < 2 seconds,  so we choose a 5 sec status interval.  Regardless of what timeout value you use, you will always have to merge records together.
racluster.1 will merge them together, regardless of time, and deal with direction very well, and racluster.1 is stateful in its aggregation.

So I would suggest:

   argus -r “dump.pcap” -w - | racluster -r - -c,

That should give you the behavior you’re interested in ...

**Comment by openargus** [comment]
Oh … sorry for the early send …
And racluster has a pretty extensive configuration that allows you to specify the aggregation time for pushes, the flow idle time, stateful pushes, etc … , which can be specified on a per flow bases, ports, protocols, addresses, you name it …

Checkout racluster.conf man page …
Carter

**Comment by mielverkerken** [comment]
Hi Carter,

Thank you very much for the information and for pointing me in the right direction.
Very much appreciated.

Miel

**Comment by mielverkerken** [comment]
I reviewed the documentation and made an attempt at configuring `racluster`. But I fail to configure the stateful push. Using the `racluster` configuration below I tried the following command:

```sh
argus -r "dump.pcap" -S 1s -w - | racluster -f racluster.conf -r - -c, > "argus.csv"
```

```
# racluster.conf - Configuration to cluster flows until termination

# Preserve fields and don't report aggregation metrics
RACLUSTER_PRESERVE_FIELDS=yes
RACLUSTER_REPORT_AGGREGATION=no
RACLUSTER_AUTO_CORRECTION=no

# Cluster all flows based on the default 5-tuple (saddr, daddr, proto, sport, dport)
# but ensure that terminated flows are not merged with new flows.
filter="" model="saddr daddr proto sport dport" status=0 idle=15
```

This makes `racluster` output the aggregated argus flows after 15s of inactivity, even if the flows terminated earlier (TCP RST or FIN). This works well, but if within these 15s a new flow starts using the same default 5 tuple, the flows are merged. Is it possible to output the flow on termination and remove it from the cache? This would prevent terminated flows to be merged with new flows reusing the same 5 tuple.

**Comment by openargus** [comment]
Can you share a packet file that demonstrates the condition and if there is a specific flow to track ...   we can fix, if there is a bug ...Carter Carter Bullard • CEO250 E 53rd Street Suite 501New York, New York 10022Phone +1.212.588.9133 • Mobile +1.917.497.9494On Aug 24, 2024, at 1:54 PM, Miel Verkerken ***@***.***> wrote:﻿
I reviewed the documentation and made an attempt at configuring racluster. But I fail to configure the stateful push. Using the racluster configuration below I tried the following command:
argus -r "dump.pcap" -S 1s -w - | racluster -f racluster.conf -r - -c, > "argus.csv"
# racluster.conf - Configuration to cluster flows until termination

# Preserve fields and don't report aggregation metrics
RACLUSTER_PRESERVE_FIELDS=yes
RACLUSTER_REPORT_AGGREGATION=no
RACLUSTER_AUTO_CORRECTION=no

# Cluster all flows based on the default 5-tuple (saddr, daddr, proto, sport, dport)
# but ensure that terminated flows are not merged with new flows.
filter="" model="saddr daddr proto sport dport" status=0 idle=15

This makes racluster output the aggregated argus flows after 15s of inactivity, even if the flows terminated earlier (TCP RST or FIN). This works well, but if within these 15s a new flow starts using the same default 5 tuple, the flows are merged. Is it possible to output the flow on termination and remove it from the cache? This would prevent terminated flows to be merged with new flows reusing the same 5 tuple.

**Comment by mielverkerken** [comment]
The attached archive contains `dump.pcap` and `argus.csv` as extracted by the commands above. The network capture contains ssh bruteforce login attempts.

The flow being merged is outputted as:
```
08/23.18:40:15.810091, e g      ,tcp,192.168.19.190,57556, ->,192.168.249.127,22,111,16704,FIN
```

[capture.zip](https://github.com/user-attachments/files/16737955/capture.zip)

**Comment by mielverkerken** [comment]
Nice effort! 

Regarding the naming, Wireshark uses "TCP Port numbers reused", thus `ARGUS_PORT_REUSE` or `TCP_PORT_REUSE` covers the meaning well. 

Would you like me to open an issue in the client repository?

**Comment by mielverkerken** [comment]
Your change to `argus` already allows me to get the behavior I was after. I just tested it using the command below:

```sh
argus -r "dump.pcap" -S 15s -w - | ra -r - -c, > "argus.csv"
```

Since `argus` now flushes the cached record when `TH_SYN` is seen after TCP close, I can set `-S` in the argus command to a timeout value greater than the duration of my longest flow. This results in a single row for each flow without the need for aggregation.

Thanks!

**Comment by openargus** [comment]
Yes, I believe we should work on the client side on this a bit.

Whenever you add a new feature to the argus data set, there is a bit of work needed to support it …
   1. Printing the feature
   2. Filtering for the feature
   3. Aggregating the feature
   4. Sorting by feature
   5. Counting the occurrence of the feature (basic analytics)
   6. Anonymizing the feature (if needed).

The aggregating is the most interesting, so I’ll think about it a bit this week, but the rest is easy to knock off, just need to track it.

Carter

**Comment by openargus** [comment]
Great !!!  I found an issue with the fix (processing the SYN of the reuse flow twice), and corrected that.  We were reporting packet retransmission on the SYN …. So do grab the new code ...
As I mentioned earlier, there will eventually be a flow that will just go over whatever status interval you choose, so we’ll need to add support for aggregation.
Carter

**Comment by openargus** [comment]
I’ve pushed to the main clients branch, some new support for the new TCP port reuse detection in argus.
With the new mods to argus, the supplied packet file generates these default flows, and the new clients print them out as …

% argus -r packet.file -w - | ra

                 StartTime        Dur      Flgs  Proto            SrcAddr  Sport   Dir            DstAddr  Dport  SrcPkts  DstPkts     SrcBytes     DstBytes State 
2024/08/23.14:40:15.810091   3.946081  e           tcp     192.168.19.190.57556     ->    192.168.249.127.22           16       18         2496         3413   CON
2024/08/23.14:40:22.328849   4.383313  e           tcp     192.168.19.190.57556     ->    192.168.249.127.22            6       12          892         1224   CON
2024/08/23.14:40:28.250082   0.000666  e           tcp     192.168.19.190.57556     ->    192.168.249.127.22            1        3           66          294   FIN
2024/08/23.14:40:29.865047   4.047113  e R         tcp     192.168.19.190.57556     ->    192.168.249.127.22           14       19         2364         3479   CON
2024/08/23.14:40:35.410217   4.957940  e           tcp     192.168.19.190.57556     ->    192.168.249.127.22            6       12          892         1224   CON
2024/08/23.14:40:42.489299   0.000719  e           tcp     192.168.19.190.57556     ->    192.168.249.127.22            1        3           66          294   FIN

Please note the ‘R’ in the flags field, indicating that argus detected port reuse on this flow record.

When we aggregate these records we get this default result …

% argus -r packet.file -w - | racluster -s +trans - not man
                 StartTime        Dur      Flgs  Proto            SrcAddr  Sport   Dir            DstAddr  Dport  SrcPkts  DstPkts     SrcBytes     DstBytes State  Trans 
2024/08/23.14:40:15.810091  26.679928  e R         tcp     192.168.19.190.57556     ->    192.168.249.127.22           44       67         6776         9928   FIN      6


This preserves the ARGUS_PORT_REUSE indication regardless of the level of aggregation, as long as all the flows are TCP flows … (since it is a TCP behavior).
Still a bit of work to do to tease out the independent flows when using default aggregation, but this is a good start ...

Carter

>

**Comment by mielverkerken** [comment]
Hi Carter,

Great work moving forward! 

Regarding aggregation, is there a scenario where you would want to aggregate TCP flows if a new flow reuses the same 5-tuple (or other specified aggregation criteria)? The default behavior should be considered. If you need to maintain the current behavior, an additional command-line option should be provided in the client tools to prevent the automatic merging of these flows.

**Comment by openargus** [comment]
Hey Miel,
Aggregation is one of the power analytics for flow data … it is the basis for most of the behavioral work we do in argus, and its a huge chunk of what the large sites do with flow data to manage the loads.  So yes, there are many more reasons to aggregate the flows together than to keep them apart.

When you add a new feature, how you treat that feature in aggregation can be HUGE … say you’re interested in being able to “see” that a specific host used TCP Port Reuse … I would be interested in knowing that for the last 6 months ...  If aggregation can preserve the reuse indication, then I can build a system that can tell me who has experienced port reuse over the last 182 days (6 months) … and if I do it in a general way, then I can “ know " that condition along with other conditions, such as ICMP redirect attacks, masquerade, lateral movement, port spanning, stepping stones or some form of brute force, all in the same database table, without actually analyzing specifically for these behaviors.  That’s pretty cooool.

So with racluster.1, I can run a program like this …

   racluster -R /path/to/argus/archive/2024/08/25 -m matrix proto -w ra.daily.matrix.proto.2024.08.25

This will create single argus records for each unique [src, dst, proto ] for the entire day …. This can provide data reduction of 1000:1 generally, in most networks.  If aggregation is done well, you can get a lot of good information from the reduced data set … 

From here you can do something like this:

   ra -r ra.daily.matrix.proto.2024.08.25 - reuse

And see all the ip address pairs that experienced a TCP port reuse. 
Now if I aggregate all the daily aggregates, I can build a yearly aggregate table, so that I can query, “have I seen TCP port reuse this year ?"

When you get to processing petabytes worth of flow data, and you want to query it over long periods of time, being about to aggregate with good feature retention is the key …

Carter

**Comment by mielverkerken** [comment]
Hi Carter,

Thanks for the explanation! I have no experience processing flow data in such huge quantities or over such long periods, but this clearly shows the power of the client tooling with argus.

- Miel

**Comment by openargus** [comment]
As a test of the new ARGUS_PORT_REUSE feature aggregation, aggregation using default configurations for argus and the clients needs a bit of tweaking.  However, aggregation and filtering is working very well.  Here are some examples:

Here we just count the flow records and print some basic aggregate counters from all the packets in the capture file provided:

apophis:capture carter$ argus -r dump*pcap -w - | racount
racount   records     total_pkts     src_pkts       dst_pkts       total_bytes        src_bytes          dst_bytes
    sum   1674        33331          13626          19705          5180206            2108276            3071930        
   

There is a set of status flow records in the packet capture that represent TCP port reuse, out of the 1674 flows that are in the capture file.
We can filter using the source port to see all the status records that argus generates by default, that are involved.
Just happens that they all are using src port 57556, so we can use that as a filter … “ - src port 57556 ”.
Here we add the ’number of transactions’ used to generate the flow record with the  “ -s +trans “ filter.

apophis:capture carter$ argus -r dump.pcap -w - | ra -s +trans - src port 57556
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans 
08/23.14:40:15.810091   3.946081  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22           34       5909   CON      1
08/23.14:40:22.328849   4.383313  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22           18       2116   CON      1
08/23.14:40:28.250082   0.000666  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22            4        360   FIN      1
08/23.14:40:29.865047   4.047113  e R         tcp       192.168.19.190.57556     ->      192.168.249.127.22           33       5843   CON      1
08/23.14:40:35.410217   4.957940  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22           18       2116   CON      1
08/23.14:40:42.489299   0.000719  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22            4        360   FIN      1

Argus tags the first recognized ‘ TCP port reuse ‘ flow in the set, with an ‘R’ in the flgs field.


You can use a filter to select just this one flow record. “ - reuse “.

apophis:capture carter$ argus -r dump.pcap -w - | ra -s +trans - reuse
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans 
08/23.14:40:29.865047   4.047113  e R         tcp       192.168.19.190.57556     ->      192.168.249.127.22           33       5843   CON      1



Default aggregation is best done with racluster.1, although rabins.1, and ratop.1 will also do the same thing.  
Generally, racluster.1 will aggregate status flow records together into one transactional record, using the 5-tuple flow ids (src addr, dst addr, proto, src port, dst port).
Here we’ll send all the flows that argus generates to racluster, to perform default aggregate, but we’ll filter for just the “ src port 57556 “ flows.

apophis:capture carter$ argus -r dump.pcap -w - | racluster -s +trans - src port 57556
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans 
08/23.14:40:15.810091  26.679928  e R         tcp       192.168.19.190.57556     ->      192.168.249.127.22          111      16704   FIN      6

The ’trans’ field reveals that racluster.1 merged 6 status records to generate the aggregate flow. This is exactly what we would expect, as all share the same 5-tuple ids.
The key here, is that the ‘R’ indication is preserved.


racluster.1, when given all 1674 flows from the dump.pcap file, will aggregate all the records together using the default 5-tuple flow id’s, reducing the file, but retaining most of the flow information.  

apophis:capture carter$ argus -r dump*pcap -w - | racluster -w - | racount
racount   records     total_pkts     src_pkts       dst_pkts       total_bytes        src_bytes          dst_bytes
    sum   672         33331          13626          19705          5180206            2108276            3071930 

Compared with the racount.1 output, all the metrics (pkts, bytes, etc…) are the same, but the record count is reduced by 60%.


We can filter the aggregated output stream, to pick out just the flows where TCP port reuse was seen … using the “- reuse “ filter.

apophis:capture carter$ argus -r dump.pcap -w - | racluster -w - | ra -s +trans - reuse 
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans 
08/23.14:40:15.810091  26.679928  e R         tcp       192.168.19.190.57556     ->      192.168.249.127.22          111      16704   FIN      6


If we change the aggregation model to remove the source port from the 5-tuple key,  you get good reduction, and we retain the ‘ TCP port reuse ‘ seen.

apophis:capture carter$ argus -r dump.pcap -w - | racluster -m -sport -s +trans 
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans 
08/23.14:34:07.497230 701.166321  e R         tcp       192.168.19.190           ->      192.168.249.127.22        33331    5180206   FIN   1674


And if we change the aggregation model to only track the protocol,  you get great data reduction, and we still retain the ‘ TCP port reuse ‘ seen.

apophis:capture carter$ argus -r dump.pcap -w - | racluster -m proto -s +trans 
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans 
08/23.14:34:07.497230 701.166321  e R         tcp       192.168.19.190           ->      192.168.249.127.22        33331    5180206   FIN   1674

**Comment by openargus** [comment]
As a test of the new ARGUS_PORT_REUSE feature aggregation, aggregation using default configurations for argus and the clients needs a bit of tweaking.  However, aggregation and filtering is working very well.  Here are some examples:

Here we just count the flow records and print some basic aggregate counters from all the packets in the capture file provided:

```
apophis:capture carter$ argus -r dump*pcap -w - | racount
racount   records     total_pkts     src_pkts       dst_pkts       total_bytes        src_bytes          dst_bytes
    sum   1674        33331          13626          19705          5180206            2108276            3071930
```


There is a set of status flow records in the packet capture that represent TCP port reuse, out of the 1674 flows that are in the capture file. We can filter using the source port to see all the status records that argus generates by default, that are involved.  Just happens that they all are using src port 57556, so we can use that as a filter … “ - src port 57556 ”.

Here we add the ’number of transactions’ used to generate the flow record with the  “ -s +trans “ filter.

```
apophis:capture carter$ argus -r dump.pcap -w - | ra -s +trans - src port 57556
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans
08/23.14:40:15.810091   3.946081  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22           34       5909   CON      1
08/23.14:40:22.328849   4.383313  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22           18       2116   CON      1
08/23.14:40:28.250082   0.000666  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22            4        360   FIN      1
08/23.14:40:29.865047   4.047113  e R         tcp       192.168.19.190.57556     ->      192.168.249.127.22           33       5843   CON      1
08/23.14:40:35.410217   4.957940  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22           18       2116   CON      1
08/23.14:40:42.489299   0.000719  e           tcp       192.168.19.190.57556     ->      192.168.249.127.22            4        360   FIN      1

```
Argus tags the first recognized ‘ TCP port reuse ‘ flow in the set, with an ‘R’ in the flgs field.  You can use a filter to select just this one flow record. “ - reuse “.

```
apophis:capture carter$ argus -r dump.pcap -w - | ra -s +trans - reuse
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans
08/23.14:40:29.865047   4.047113  e R         tcp       192.168.19.190.57556     ->      192.168.249.127.22           33       5843   CON      1

```


Default aggregation is best done with racluster.1, although rabins.1, and ratop.1 will also do the same thing.  Generally, racluster.1 will aggregate status flow records together into one transactional record, using the 5-tuple flow ids (src addr, dst addr, proto, src port, dst port).  Here we’ll send all the flows that argus generates to racluster, to perform default aggregate, but we’ll filter for just the “ src port 57556 “ flows.

```
apophis:capture carter$ argus -r dump.pcap -w - | racluster -s +trans - src port 57556
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans
08/23.14:40:15.810091  26.679928  e R         tcp       192.168.19.190.57556     ->      192.168.249.127.22          111      16704   FIN      6

```
The ’trans’ field reveals that racluster.1 merged 6 status records to generate the aggregate flow. This is exactly what we would expect, as all share the same 5-tuple ids.
The key here, is that the ‘R’ indication is preserved.


racluster.1, when given all 1674 flows from the dump.pcap file, will aggregate all the records together using the default 5-tuple flow id’s, reducing the file, but retaining most of the flow information.

```
apophis:capture carter$ argus -r dump*pcap -w - | racluster -w - | racount
racount   records     total_pkts     src_pkts       dst_pkts       total_bytes        src_bytes          dst_bytes
    sum   672         33331          13626          19705          5180206            2108276            3071930
```

Compared with the racount.1 output, all the metrics (pkts, bytes, etc…) are the same, but the record count is reduced by 60%.


We can filter the aggregated output stream, to pick out just the flows where TCP port reuse was seen … using the “- reuse “ filter.

```
apophis:capture carter$ argus -r dump.pcap -w - | racluster -w - | ra -s +trans - reuse
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans
08/23.14:40:15.810091  26.679928  e R         tcp       192.168.19.190.57556     ->      192.168.249.127.22          111      16704   FIN      6
```


If we change the aggregation model to remove the source port from the 5-tuple key,  you get good reduction, and we retain the ‘ TCP port reuse ‘ seen indicator.

```
apophis:capture carter$ argus -r dump.pcap -w - | racluster -m -sport -s +trans
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans
08/23.14:34:07.497230 701.166321  e R         tcp       192.168.19.190           ->      192.168.249.127.22        33331    5180206   FIN   1674
```


And if we change the aggregation model to only track the protocol,  you get great data reduction, and we still retain the ‘ TCP port reuse ‘ seen.

```
apophis:capture carter$ argus -r dump.pcap -w - | racluster -m proto -s +trans
            StartTime        Dur      Flgs  Proto              SrcAddr  Sport   Dir              DstAddr  Dport  TotPkts   TotBytes State  Trans
08/23.14:34:07.497230 701.166321  e R         tcp       192.168.19.190           ->      192.168.249.127.22        33331    5180206   FIN   1674
```
