### ISSUE TITLE
License discrepancy

### ISSUE THREAD

**Issue by gromgit** [openargus/argus#4]
Hi! I help out with the [Homebrew project](https://brew.sh), and our formula audit tool led me to a licensing discrepancy in Argus. In the language of [SPDX license identifiers](https://spdx.org/licenses/), here's what I'm seeing:
* License text on Argus website: `GPL-2.0-only`
* Argus source code comments: `GPL-2.0-or-later`
* Argus `COPYING` license file: `GPL-3.0`

Could you please clarify the license situation with the necessary changes? Thanks much!

**Comment by openargus** [comment]
Hey Adrian,
The web site is stale ... Should be 2 or later ... Is there a problem with 2 only and homebrew  ???

Carter

**Comment by gromgit** [comment]
Thanks for the clarification, Carter! It's not a pressing problem, just that an out-of-date SPDX identifier on the [Argus Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/argus.rb) led me to look deeper into the Argus licensing situation, then I noticed that the formula was taking its cue from GitHub. Since the `COPYING` file in the source tree is for GPL-3.0, GitHub also claimed that, which was at odds with the `README`.

**Comment by openargus** [comment]
Hey Gromgit !!!   So I've updated the README in master-dev branch to conform to the COPYING file ... we're on 3 or later for consistency ... will take a few days to find the references on the website, so hopefully this will help !!!

I should merge the master-dev branch into master in a few days ...

**Comment by gromgit** [comment]
Good to know, thanks much for the heads-up!
